### ISSUE TITLE
WBTC sent to WBTC address 

### ISSUE THREAD

**Issue by rggithubether** [WrappedBTC/bitcoin-token-smart-contracts#50]
Hello, PLEASE HELP! 
I've made a mistake transferring my WBTC from coinbase exchange to Coinbase wallet. Instead of sending to my wallet ERC20 address, I've sent to the same WBTC contract address. heres the txn for ur reference, 

https://etherscan.io/tx/0x98f6e568a3cae28a1f9bd205c8ca2b994ddb702e94b72fa590b62367d3ad7033

it's not a lot of money but > $700 is a lot for me.  I got this github link from https://twitter.com/mosayeri.
if u need further info i can be reached at https://twitter.com/rgcoin1126. 

Thank u so much in advance.

**Comment by rggithubether** [comment]
hello? can anyone please help me on this?

**Comment by GodLovesme324** [comment]
Kindly contact the Support team to fix the issue below is their livechat link https://direct.lc.chat/14756535/

**Comment by rggithubether** [comment]
@yaronvel would u be able to assist me?

**Comment by ravz** [comment]
good luck, I've been trying for 2 years!

**Comment by rggithubether** [comment]
@ravz any DAO people reached  out to u?

**Comment by rggithubether** [comment]
Hello WBTC DAO, 

This is the txn hash for this issue.

https://etherscan.io/tx/0x1f1c8971dec959d38bcaa5606eb474d028617752240727692cd5ef21a435d847?fbclid=IwAR0W3fBY8HmJEJBuG_pWHkGQ1HyMYb18uph9WkwQbzgw9S9j-bZ07Y3tTAo

As stated earlier, I was trying to move my WBTC from Coinbase Central Exchange to Coinbase Wallet. Instead of using my wallet's ERC20 address, I accidentally copied the same WBTC contract address. 

I will reach out to Coinbase Support to check if its possible to get a verifiable process to move back my WBTC to its origin.

Thank you.

**Comment by rggithubether** [comment]
Hello WBTC DAO,

Here's the response I got from Coinbase Support.

"I totally understand the confusion this has caused you but the only support team who can help you retrieve the funds is the receiving platform of your transactions. Coinbase don't have the instructions on how to do that since the transaction was not in Coinbase anymore.

Now, regarding your question, the only team who can answer that is the WBTC Dao platform. You can ask help from them since they have your transactions and not us, "

**Comment by rggithubether** [comment]
additional response from Coinbase Support,

"What I'm saying is, they're the one who can best help you retrieve the funds and not us, Coinbase. So, I highly suggest to ask for their full cooperation and instructions on how to do that.

Also, I can't provide you the information that you are asking for security purposes."

**Comment by ravz** [comment]
@rggithubether Coinbase won't be able to assist you, only the WBTC team. We're trying to push for this PR to be processed https://github.com/WrappedBTC/DAO/pull/12 which will allow them the ability to reverse those transactions.

**Comment by rggithubether** [comment]
thank u @ravz

**Comment by joekoh-bg** [comment]
@rggithubether right now we are only able to send back to the address that the tokens were transferred from. Since this particular transaction originated from a CEX address, we will need to coordinate with Coinbase on how to get this returned back to them, so they can move it back to your wallet. Have you reached out to them? What have they said?

**Comment by rggithubether** [comment]
hi @joekoh-bg yes many times. this is what i got from coinbase.  so helpless with the situation...would it be possible to send me DEX wallet since sending it back to CEX is a very difficult situation? 

![cb-wbtc-issue-3](https://user-images.githubusercontent.com/118643701/230234206-c08bf5f4-aa59-4c9c-a6cc-936ac0fc1d77.JPG)
![cb-wbtc-issue-2](https://user-images.githubusercontent.com/118643701/230234210-31666eec-f2fd-4589-baa0-a641776bbf47.JPG)
![cb-wbtc-issue-1](https://user-images.githubusercontent.com/118643701/230234212-b9b76c17-ddf1-485f-bf20-83fc2d37eb73.JPG)

**Comment by ravz** [comment]
@rggithubether you need to ask Coinbase if they will credit your account balance if the transaction is returned to their internal wallet

**Comment by ravz** [comment]
hi @joekoh-bg is there any ETA on when these return transactions will execute? Has been 18 months since I sent.

**Comment by rggithubether** [comment]
hi @joekoh-bg @ravz 
i reached out again to CB today, and here's the response that i got (see below). really need this WBTC back to me please.
im on a dead end with Coinbase CEX here, is it possible to airdrop to my Coinbase DEX wallet?  

this is the receipt,
https://etherscan.io/tx/0x1f1c8971dec959d38bcaa5606eb474d028617752240727692cd5ef21a435d847?fbclid=IwAR0W3fBY8HmJEJBuG_pWHkGQ1HyMYb18uph9WkwQbzgw9S9j-bZ07Y3tTAo

![wbtc-cb-issue-7](https://user-images.githubusercontent.com/118643701/231023341-4ce913b1-f3fe-4c6c-b671-e6988d5bc73a.JPG)
![wbtc-cb-issue-8](https://user-images.githubusercontent.com/118643701/231023346-1b1171e1-4dff-454e-9553-23bf0099555f.JPG)
![wbtc-cb-issue-9](https://user-images.githubusercontent.com/118643701/231023350-0179eb81-669b-4e1a-9ea9-6bf2fc956f6c.JPG)

**Comment by rggithubether** [comment]
hello @joekoh-bg kindly advise thank u

**Comment by rggithubether** [comment]
hello @joekoh-bg any update please? thank u

**Comment by khademreza688** [comment]
>

**Comment by rggithubether** [comment]
@joekoh-bg hi just touching base if u have any update on this? Thank u

**Comment by rggithubether** [comment]
Hi @joekoh-bg please advise any update on this

**Comment by rggithubether** [comment]
@joekoh-bg any update on this please?

**Comment by joekoh-bg** [comment]
@rggithubether do you have a Telegram handle?

**Comment by Smotheredhope80** [comment]
I am in the same situation except, that I was trying to withdraw USDC from Coinbase into my Arbitrium wallet so I could buy some WBTC but I accidently sent it to the WBTC contract address on Arbitrium. It sucks cause I know that it will be a 2 step process if funds do get reverted. Contract send back to owner (Coinbase) then I have to convince Coinbase that it was me that the funds need to go to.  

TX Hash 0xc0e75d75c6dba7062cea3e673c90fb4a602dcb039cd1e9f6cdbb2e42764dbb0c

https://arbiscan.io/tx/0xc0e75d75c6dba7062cea3e673c90fb4a602dcb039cd1e9f6cdbb2e42764dbb0c

**Comment by ravz** [comment]
@Smotheredhope80 good luck
myself and others have been waiting 2.5 years for DAO to approve a single transaction

**Comment by rggithubether** [comment]
> @rggithubether do you have a Telegram handle?

@joekoh-bg no I don't have any telegram handle

**Comment by rggithubether** [comment]
@tranvictor @joekoh-bg any update please?

**Comment by joekoh-bg** [comment]
@rggithubether I have emailed Coinbase support seeing if they will help verify your's (and other folks') account identities and also provide us with an address for where we can return WBTC to.

**Comment by Smotheredhope80** [comment]
Thank you for the update @joekoh-bg and all of your work on this. Do you know if this is just for the WBTC contract on the Ethereum Network or is the Arbitrum WBTC contract (0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f) also being cleared of accidental token sends?

**Comment by rggithubether** [comment]
> @rggithubether I have emailed Coinbase support seeing if they will help verify your's (and other folks') account identities and also provide us with an address for where we can return WBTC to.

@joekoh-bg I really appreciate you. Thank you for the update!

**Comment by rggithubether** [comment]
> > @rggithubether I have emailed Coinbase support seeing if they will help verify your's (and other folks') account identities and also provide us with an address for where we can return WBTC to.
> 
> @joekoh-bg I really appreciate you. Thank you for the update! 

Hi @joekoh-bg pls advise if u heard back from CB? Thank u.

**Comment by rggithubether** [comment]
@joekoh-bg any news? thanks in advance.

**Comment by rggithubether** [comment]
@joekoh-bg @tranvictor any update guys?  please advise.

**Comment by joekoh-bg** [comment]
Still trying to get through. Their chat & email was a dead end. Hoping social media & employee contact bears more fruit.

**Comment by rggithubether** [comment]
> Still trying to get through. Their chat & email was a dead end. Hoping social media & employee contact bears more fruit.

I've tried reaching out to them, they used proxy chains and won't share any other info on this. Is there any other options to return my WBTC? this is almost a year now.

**Comment by joekoh-bg** [comment]
Give me a few days to finish my conversations with them through these new avenues and I will report back.

**Comment by rggithubether** [comment]
> Give me a few days to finish my conversations with them through these new avenues and I will report back.

thank you so much

**Comment by joekoh-bg** [comment]
@rggithubether Coinbase has reached out asking for proof of transactions. I sent them this hash: https://etherscan.io/tx/0x1f1c8971dec959d38bcaa5606eb474d028617752240727692cd5ef21a435d847

and am awaiting reply for them to confirm where the DAO should send back to.

**Comment by rggithubether** [comment]
> @rggithubether Coinbase has reached out asking for proof of transactions. I sent them this hash: https://etherscan.io/tx/0x1f1c8971dec959d38bcaa5606eb474d028617752240727692cd5ef21a435d847
> 
> and am awaiting reply for them to confirm where the DAO should send back to.

thank you for the update @joekoh-bg 
the hash is correct, 
https://etherscan.io/tx/0x1f1c8971dec959d38bcaa5606eb474d028617752240727692cd5ef21a435d847

this is also proof of receipt from my mobile (coinbase apps).
![WBTC-transaction-11-19-2022](https://github.com/WrappedBTC/bitcoin-token-smart-contracts/assets/118643701/fd2821fb-ae99-4f34-a4ac-e8283266f40a)

**Comment by joekoh-bg** [comment]
@rggithubether great news! Coinbase has agreed to help returning the WBTC in this transaction: https://etherscan.io/tx/0x1f1c8971dec959d38bcaa5606eb474d028617752240727692cd5ef21a435d847

The DAO has not yet started to reconcile any refunds for CEX sends, so please be patient with us. We are currently in the midst of returning individual user funds to their original addresses. We are on the last step and should be able to complete that relatively soon.

Once that is completed, we can begin to work to return your funds to Coinbase.

**Comment by rggithubether** [comment]
> @rggithubether great news! Coinbase has agreed to help returning the WBTC in this transaction: https://etherscan.io/tx/0x1f1c8971dec959d38bcaa5606eb474d028617752240727692cd5ef21a435d847
> 
> 
> 
> The DAO has not yet started to reconcile any refunds for CEX sends, so please be patient with us. We are currently in the midst of returning individual user funds to their original addresses. We are on the last step and should be able to complete that relatively soon.
> 
> 
> 
> Once that is completed, we can begin to work to return your funds to Coinbase.

Great news! Thank you so much! much appreciated!

**Comment by rggithubether** [comment]
@joekoh-bg hi just touching base to check if the DAO CEX refund approval is complete? thank you.

**Comment by rggithubether** [comment]
@joekoh-bg hi any update sir?

**Comment by rggithubether** [comment]
@joekoh-bg hi any news sir?

**Comment by joekoh-bg** [comment]
Nothing to update on. DAO still dragging their feet on the air drop step.

**Comment by rggithubether** [comment]
@joekoh-bg thank u. is there anything we can do to follow up the DAO? my worry is this will drag on and Coinbase gonna forget then we'll start all over again.

**Comment by rggithubether** [comment]
@tranvictor is there anything you can help with to get the momentum going with the DAO please? thanks in advance. @joekoh-bg

**Comment by tranvictor** [comment]
Hi everyone, i have inited the tx to distribute just now, waiting for 2 more signers, please take a look here: https://app.safe.global/home?safe=eth:0xA1F7bB557c1fe6Ded1EE6b1775E5B2d2f7598ae4

**Comment by rggithubether** [comment]
> Hi everyone, i have inited the tx to distribute just now, waiting for 2 more signers, please take a look here: https://app.safe.global/home?safe=eth:0xA1F7bB557c1fe6Ded1EE6b1775E5B2d2f7598ae4

@tranvictor thank you for the update.
@joekoh-bg

**Comment by rggithubether** [comment]
@tranvictor @joekoh-bg  
how can i check which one is mine in this transaction?

**Comment by joekoh-bg** [comment]
hi @rggithubether, your refund was not included in this batch. This set specifically did not include the refund to any CEX addresses which is where your's was from. We will handle this refund separately. I am going to bring up your refund to the DAO today, and hopefully can resolve in the coming weeks.

**Comment by rggithubether** [comment]
@joekoh-bg understood. Thanks for the update.

**Comment by rggithubether** [comment]
@joekoh-bg hi any updates?

**Comment by rggithubether** [comment]
> @rggithubether the vote to return WBTC to that Coinbase address is currently taking place. We just need 1 more person to finalize. Will let you know here as soon as it's returned.

@joekoh-bg thank you so much sir! I appreciate u.

**Comment by joekoh-bg** [comment]
Hi @rggithubether, excellent news. The DAO sent the WBTC back to Coinbase's address here: https://etherscan.io/tx/0x0d71f0ebda1dd478997bd964c017dbc6ab29a28ea3647e1d2793f1c1f97a5782

From your Coinbase account email, send an email to Coinbase support (help@coinbase.com) and reference the case number #16137373 telling them that the WBTC DAO refunded their address and with the WBTC and the DAO has just sent it back. Thus, Coinbase should refund your wallet now. I will also confirm with them in the open ticket that I have with them too. Almost done!

**Comment by rggithubether** [comment]
@joekoh-bg thank you so much! I will watch out for the refund. Appreciate you guys. 🙏🏼

**Comment by rggithubether** [comment]
> Hi @rggithubether, excellent news. The DAO sent the WBTC back to Coinbase's address here: https://etherscan.io/tx/0x0d71f0ebda1dd478997bd964c017dbc6ab29a28ea3647e1d2793f1c1f97a5782
> 
> From your Coinbase account email, send an email to Coinbase support ([help@coinbase.com](mailto:help@coinbase.com)) and reference the case number #16137373 telling them that the WBTC DAO refunded their address and with the WBTC and the DAO has just sent it back. Thus, Coinbase should refund your wallet now. I will also confirm with them in the open ticket that I have with them too. Almost done!

thank you again @joekoh-bg  i just emailed CB with the case ref #, i havent seen the WBTC returned to my account.  I will closely watch.

**Comment by joekoh-bg** [comment]
@rggithubether sorry, I should have said in my last comment that you need to send them the txn hash from today too. So please send them the etherscan link so they can confirm on their end.

**Comment by rggithubether** [comment]
> @rggithubether sorry, I should have said in my last comment that you need to send them the txn hash from today too. So please send them the etherscan link so they can confirm on their end.

@joekoh-bg yes provided the etherscan. i just chatted with the customer service on help support as the email is a non-reply function.
they have confirmed that the transaction is in-progress. and will watch out closely.  again, thank u guys so much! you guys are awesome!

**Comment by rggithubether** [comment]
hi @joekoh-bg as of today, this is response i got from CB. 

![cb-chat-case-16137373-10-26-23_3](https://github.com/WrappedBTC/bitcoin-token-smart-contracts/assets/118643701/adc5d54e-3501-4670-9c24-ce5568d71fc5)
![cb-chat-case-16137373-10-26-23_2](https://github.com/WrappedBTC/bitcoin-token-smart-contracts/assets/118643701/f3af98a9-134c-46b3-84a5-fa0de71746dc)
![cb-chat-case-16137373-10-26-23](https://github.com/WrappedBTC/bitcoin-token-smart-contracts/assets/118643701/9feef60f-0df1-4134-a1f3-380df67c9478)

**Comment by rggithubether** [comment]
hi @joekoh-bg i haven't received my WBTC from CB yet, any idea what's going on?

**Comment by rggithubether** [comment]
hi @joekoh-bg CB is just going back and forth with me with regards to the refund. according to them they sent an email to j*ek*h@b*tgo.com with regards to following up with the investigation.  i'm assuming that is your email address.

**Comment by rggithubether** [comment]
@joekoh-bg @tranvictor this is the response i got from CB today, 11/6/23 - this is so frustrating man. 
![CB-11-6-23-3](https://github.com/WrappedBTC/bitcoin-token-smart-contracts/assets/118643701/93656231-b44e-4fb6-89b5-6e0b93cacb2b)
![CB-11-6-23-2](https://github.com/WrappedBTC/bitcoin-token-smart-contracts/assets/118643701/d0e2a64a-57b8-403e-bf32-304c563c40de)
![CB-11-6-23-1](https://github.com/WrappedBTC/bitcoin-token-smart-contracts/assets/118643701/18be148d-33ba-4f4b-b557-bed8d91128bd)

**Comment by rggithubether** [comment]
@joekoh-bg @tranvictor  
I hit a wall with CB CEX - this so frustrating**.  is there a way i can get my refund to my CB DEX instead?

**Comment by rggithubether** [comment]
@joekoh-bg per CB, they sent an email on 10/23. i didnt get it looks like it was sent out to you.
please advise. 
![cb-11-6-23-email](https://github.com/WrappedBTC/bitcoin-token-smart-contracts/assets/118643701/9dc34a85-5e43-433f-9fcc-89d0505dda09)

**Comment by rggithubether** [comment]
Hi @joekoh-bg last time u mentioned that Coinbase has agreed to return my WBTC, based on my follow ups with them, it seems that they don't. Please advise.

**Comment by joekoh-bg** [comment]
@rggithubether what email are you using to reach out to them?

**Comment by joekoh-bg** [comment]
I will ask to see what email they are using, in the meantime, you can see
their frustration/inability to get a relevant response in the last several
messages of this GitHub ticket:
https://github.com/WrappedBTC/bitcoin-token-smart-contracts/issues/50

**Comment by rggithubether** [comment]
> @rggithubether what email are you using to reach out to them?

@joekoh-bg 
i talked to CB customer agents online, they dont reply to the email you gave last time (help@coinbase.com).  my email is roniegeronimo@yahoo.com associated to the CB CEX account.  they said they sent an email to jekh@b*tgo.com for the open case on 10/23/23.   so from here, i dont know how they are going to refund my WBTC.

**Comment by rggithubether** [comment]
@joekoh-bg  everytime i reached out to them (different customer agents) - i'm like a broken record explaining the same case over and over again.  i dont think they want my WBTC refunded for some reason idk.

**Comment by joekoh-bg** [comment]
@rggithubether I gave Coinbase support your email and this was the response I received:

"Hi Joe,

Thank you for this information. 

I was able to locate the case where customer reached out to us. Request for credit to customer's Coinbase account has been received and we wanted to provide you with some details on our review process as well. The investigation and review process will take up to take 4 to 5 weeks to complete.

We will notify the customer of the result when our review is complete."

**Comment by rggithubether** [comment]
hi @joekoh-bg thank you so much! i saw the email, too.

**Comment by rggithubether** [comment]
Hi @joekoh-bg 
this is the email content I got from CB. and with the link that provides the process of refunding. ![image](https://github.com/WrappedBTC/bitcoin-token-smart-contracts/assets/118643701/bb598074-5668-4881-b16b-563524c6b78e)![image](https://github.com/WrappedBTC/bitcoin-token-smart-contracts/assets/118643701/eff6feb0-5c3e-495c-8937-fb2571b429cd)
![image](https://github.com/WrappedBTC/bitcoin-token-smart-contracts/assets/118643701/9219d2c7-692c-4303-8234-c33622607d0f)
![image](https://github.com/WrappedBTC/bitcoin-token-smart-contracts/assets/118643701/b71005f6-d9f1-435e-9b2b-41ce3cd6e445)

**Comment by rggithubether** [comment]
hi @joekoh-bg my WBTC has been refunded to me. Thank you so much for all your help! happy holidays! ![image](https://github.com/WrappedBTC/bitcoin-token-smart-contracts/assets/118643701/42708b5b-3ad9-48c2-9503-22941875aeca)

**Comment by joekoh-bg** [comment]
@rggithubether excellent! Glad we were finally able to resolve this.
